# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Pierre Marchand # Website name
baseurl: "https://pierremarchand.netlify.com/" # Website URL
copyright: "" # Footer text, e.g. '© {year} Me'

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /post/**
    # Which page types are commentable?
    editable: false
    reading_time: true
    commentable: false
    show_related: false
    show_breadcrumb: true
    header:
      navbar:
        enable: false

############################
## LANGUAGE
############################

# Default language to use (if you setup multilingual support)
defaultContentLanguage: en
hasCJKLanguage: false # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir: false
removePathAccents: true # Workaround for https://github.com/gohugoio/hugo/issues/5687

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5
    - path: cj.rs/gohugo-asciinema

############################
## ADVANCED
############################

enableGitInfo: false # Get last modified date for content from Git?
summaryLength: 30
paginate: 10 # Number of items per page in paginated lists.
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
permalinks:
  event: "/talk/:slug/"
  tags: "/tag/:slug/"
  categories: "/category/:slug/"
  publication_types: "/publication-type/:slug/"
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep

# Related content.
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 0
security:
  _merge: deep
