# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

############################
## Appearance
############################

appearance:
  # Choose a theme.
  #   Latest themes (may require updating): https://sourcethemes.com/academic/themes/
  #   Browse built-in themes in `themes/academic/data/themes/`
  #   Browse user installed themes in `data/themes/`
  theme_day: ocean
  # theme_night: minimal
  day_night: true
  # # Enable users to switch between day and night mode?
  # day_night: false

  # Override the theme's font set (optional).
  #   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
  #   Browse built-in font sets in `themes/academic/data/fonts/`
  #   Browse user installed font sets in `data/fonts/`
  font: "Ocean"

  # Choose a font size.
  # Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
  font_size: "L"

############################
## Marketing
############################

marketing:
  seo:
    # Website type
    #   Improve how search engines understand your site.
    #   For personal sites, choose "Person".
    #   For organizations and projects, choose from https://schema.org/Organization#subtypes
    #   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
    site_type: Person

    # Local business type (optional)
    # If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
    local_business_type: ""

    # Organization name (optional)
    # Enter an organization or project name. Defaults to the site title from `config.toml`.
    org_name: ""

    # Description for social sharing and search engines. If undefined, superuser role is used in place.
    description: ""

    twitter: ""

  analytics:
    google_analytics: "UA-171155841-1"
    baidu_tongji: ""
  verification:
    google: ""
    baidu: ""

############################
## Site header
############################

# Main menu alignment (l = left, c = center, r = right) and logo options.
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

############################
## Site features
############################

features:
  # Enable source code highlighting? true/false
  # Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex

  # Enable LaTeX math rendering? true/false
  #   If false, you can enable math on a per page basis as needed.
  math:
    enable: false

  # Enable diagram rendering? true/false
  #   If false, you can enable diagrams on a per page basis as needed.
  diagram:
    enable: false

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack:
    enable: true

  repository:
    url: "https://github.com/PierreMarchand20/personal_webpage"
    content_dir: content
    branch: master

  # Avatars.
  # An avatar is an image that appears next to a user's name.
  # An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
  avatar:
    gravatar: false
    shape: circle

  comment:
    # Comment provider:
    #   "": Disabled
    #   "disqus": Disqus (https://disqus.com)
    #   "commento": Commento (https://commento.io)
    provider: "disqus"
    disqus:
      shortname: ""
      show_count: true
    commento:
      url: ""

  search:
    # Search provider:
    #   "": No search engine
    #   "wowchemy": Built-in search engine
    #   "algolia": Algolia (https://www.algolia.com)
    provider: wowchemy
    # Configuration of Algolia search engine.
    # Paste the values from your Algolia dashboard.
    algolia:
      app_id: ""
      api_key: ""
      index_name: ""
      show_logo: false

  map:
    # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
    # and choose a map provider below.
    #
    # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
    #   https://developers.google.com/maps/documentation/javascript/get-api-key
    # To use OpenStreetMap tiles, set `engine` to 2.
    # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
    #   https://www.mapbox.com/studio/account/tokens
    #
    # Map provider:
    #   0: No map
    #   1: Google Maps
    #   2: OpenStreetMap (Mapnik)
    #   3: OpenStreetMap (Mapbox)
    provider: "mapnik"
    api_key: ""
    zoom: 15

# Enable visitors to edit pages?
#   `repo` defines the repository URL. `editable` defines which page types can be edited.
edit_page:
  repo_url: ""
  content_dir: ""
  repo_branch: master
  editable:
    page: false
    post: false
    book: false

# Show related content at the bottom of pages?
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true

############################
## Regional Settings
############################
locale:
  # Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format: "January 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format: "15:04"
  # Address format (choose from the [address_formats] list below or add you own to the list).
  address_format: fr-fr

############################
## Advanced
############################

# Display next/previous section pager? (true/false)
section_pager: false
docs_section_pager: true # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing: true

# Show a copyright license from creativecommons.org in the site footer?
# Page specific copyright licenses are also possible by adding this option to a page's front matter.
footer:
  copyright:
    notice: "© {year} Pierre Marchand. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
abstract_length: 135

# Load CSS and JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js: []

# Configuration of publication pages.
publications:
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format: January 2006

  # Citation style ("apa" or "mla")
  citation_style: apa

# Configuration of project pages.
projects:
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view: 2
  publication_view: 4
  talk_view: 2

breadcrumb:
  page_types:
    book: true

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true
  icon:
    pack:
      ai: true
